import mongoose from 'mongoose';

const transcriptSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // The subject field represents the course or lecture name
    subject: {
      type: String,
      required: true,
    },
    // Raw transcription text as generated by speech-to-text
    rawTranscript: {
      type: String,
      required: true,
      default: '',
    },
    // Auto-generated summary from OpenAI, optional and editable by user
    summary: {
      type: String,
      default: '',
    },
    // ISO timestamp indicating when the transcription was created
    transcribedAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

const Transcript = mongoose.model('Transcript', transcriptSchema);

export default Transcript;
